services:
  app:
    container_name: "banking-application"
    image: "banking-app"
    build: .
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - banking-network
    depends_on:
      - mysqldb
      - cassandradb
  mysqldb:
    container_name: "bank-database"
    image: "mysql"
    restart: always
    ports:
      - "3307:3306"
    networks:
      - banking-network
    environment:
      MYSQL_DATABASE: bank
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  cassandradb:
    container_name: "rating-database"
    image: "cassandra"
    environment:
      CASSANDRA_CLUSTER_NAME: cassandra_cluster
    networks:
      - banking-network
    ports:
      - "9042:9042"
networks:
  banking-network: