spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/bank-db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect : "org.hibernate.dialect.MySQL8Dialect"
      ddl-auto: update
    generate-ddl: true
    show-sql: true
